services:
  stickee:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      LOG_LEVEL_GLOBAL: info
      LOG_LEVEL_STICKEE: debug

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
