services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: YOURUSERNAME
      POSTGRES_PASSWORD: YOURPASSWORD
      POSTGRES_DB: stickee

  stickee:
    image: ghcr.io/suguis/stickee:latest
    ports:
      - 8080:8080
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/stickee # In case you use a dedicated postgres you will need to change this to the necesary jdbc url.
      DB_USERNAME: YOURUSERNAME
      DB_PASSWORD: YOURPASSWORD
