spring:
  application:
    name: stickee
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  docker:
    compose:
      skip:
        in-tests: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    log-resolved-exception: false
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**/*.css
logging:
  level:
    "[cat.siesta.stickee]": ${LOG_LEVEL_STICKEE:info}
    root: ${LOG_LEVEL_GLOBAL:info}
