name: Tests 🧪

on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - pom.xml
      - compose.yaml
      - DOCKERFILE
      - .dockerignore
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 ☕
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Test with Maven 🪶
        run: ./mvnw test
  ci-cd:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: gh workflow run ci-cd.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
